# Generated by Django 5.2.15 on 2026-07-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationpolygon',
            name='color',
            field=models.CharField(default='#EF4444', max_length=20),
        ),
        migrations.AddField(
            model_name='annotationpolygon',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
